language: node_js
node_js: "node"
os: linux
dist: bionic
cache:
  directories: "node_modules"
script:
  - yarn lint
  - yarn test:unit
  - yarn build
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  strategy: git
  token: $GITHUB_TOKEN
  on:
    branch: master
