language: node_js
node_js: "node"
cache:
  directories: "node_modules"
script:
  - yarn lint
  - yarn test:unit
  - yarn build
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
